export default {
  SET_USER_LIST: 'SET_USER_LIST',
  SET_USER_POSTS: 'SET_USER_POSTS',
  SET_USER_ALBUMS: 'SET_USER_ALBUMS',
  SET_ALBUM_PHOTOS: 'SET_ALBUM_PHOTOS',
  SET_PHOTO_DETAIL: 'SET_PHOTO_DETAIL', 
} 